### ISSUE TITLE
Reading MITgcm output

### ISSUE THREAD

**Issue by xiaozhour** [gaelforget/MITgcmTools.jl#34]
Hi Gael,

I added MITgcmTools in Julia and tried to use "read_mdsio" to read in a normal MITgcm output file. 

```data=read_mdsio("U.0006307200.data")```

However, I got the following error message:  

```ERROR: UndefVarError: read_mdsio not defined```

I did add ```using MITgcmTools``` at the very beginning so I was wondering what was wrong. Does the script only read in output that is generated with ClimateModels? 

Thanks!

**Comment by gaelforget** [comment]
Not sure. Should work I think. 

Could it be that you are using a version of MITgcmTools older than 0.1.6?

What version of Julia are you using?

ps. sorry for lag in response

**Comment by xiaozhour** [comment]
Ah, I was using 0.1.5 indeed. Now it's working after I updated it. Thanks!!
