### ISSUE TITLE
Don't write to artifact dir

### ISSUE THREAD

**Issue by maleadt** [gaelforget/MITgcmTools.jl#59]
This package writes to the downloaded artifact's directory: https://github.com/gaelforget/MITgcmTools.jl/blob/d3f023c8ec71c05eeb2eec9b852dc7a92af69bd9/src/ModelSteps.jl#L75-L80

This breaks the content-addressibility of the artifact, and should really be avoided. Better to use a Scratch.jl-based scratchdir for these kinds of files.

**Comment by gaelforget** [comment]
Thanks for pointing this out

**Comment by gaelforget** [comment]
Should be fixed with v0.2.3

Thank you!
