### ISSUE TITLE
Redefinition of `fileIn` causes data to not be read in using `read_nctiles` with ECCOv4r4 data files

### ISSUE THREAD

**Issue by jbisits** [gaelforget/MITgcmTools.jl#68]
Thanks for the great package!

I have been trying to read in data from ECCOv4r4 using MITgcmTools on the llc90 grid (there is a mwe below) and the code would run but I kept getting a `gcmarray` returned that was populated with `NaN`s. The downloaded files from ECCOv4r4 that I initially tried this for was `UVELMASS_1992_01.nc` downloaded from the ECCO drive and the same granule (`OCEAN_3D_VOLUME_FLUX_mon_mean_1992-01_ECCO_V4r4_native_llc0090.nc`) from the NASA granule listing. 

I think there is a redefinition of the variable `fileIn` in line 172 of `ReadFiles.jl` causing the `gcmarray` to be populated with `NaN`s

```julia
f0=fill(NaN,mygrid.fSize[ff]...,s[3:end]...)
n0=m0[1]
for n in 1:nn
  fileIn=@sprintf("%s.%04d.nc",fileRoot,n+n0) # redefinition that means isfile(fileIn) = false
  if isfile(fileIn) #skip if no file / blank tile
    x = ClimateModels.ncread(fileIn,fldName,start,count)
        ...
```

When I run

```julia
julia> isfile(@sprintf("%s", fileIn))
true
```

but

```julia
julia> isfile(@sprintf("%s.%04d.nc",fileRoot,1))
false
```

so the condition to enter the loop to read the data is never satisfied. 
I forked this repo and removed the redefinition of `fileIn` and this solved my issue. I have opened a draft PR with this fix, but this might not skip if there is no file or blank tile?

## MWE

Using the `ECCO-GRID.nc` file from the ECCO drive to try and reproduce the [demonstration](https://gaelforget.github.io/MITgcmTools.jl/dev/functionalities_reaM/#MITgcmTools.read_nctiles) in the docs

Before fix
```julia
julia> using MITgcmTools, MeshArrays
julia> mygrid = GridSpec("LatLonCap")
julia> fileName = #path to data on my machine
julia> Depth = read_nctiles(fileName, "Depth", mygrid)
5×13 MeshArrays.gcmarray{Float64, 2, Matrix{Float64}}:
 [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]  …  [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]
 [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]     [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]
 [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]     [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]
 [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]     [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]
 [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]     [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN]
```

After fix
```julia
julia> Depth = read_nctiles(fileName, "Depth", mygrid)
5×13 MeshArrays.gcmarray{Float64, 2, Matrix{Float64}}:
 [0.0 0.0 … 3125.52 3203.08; 0.0 0.0 … 2908.5 3283.12; … ; 0.0 0.0 … 5383.54 5433.77; 0.0 0.0 … 5332.44 5367.77]  …  [3920.27 3984.9 … 2949.7 3076.34; 3809.59 3906.7 … 3126.5 3119.12; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0]
 [0.0 0.0 … 3125.52 3203.08; 0.0 0.0 … 2908.5 3283.12; … ; 0.0 0.0 … 5383.54 5433.77; 0.0 0.0 … 5332.44 5367.77]     [3920.27 3984.9 … 2949.7 3076.34; 3809.59 3906.7 … 3126.5 3119.12; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0]
 [0.0 0.0 … 3125.52 3203.08; 0.0 0.0 … 2908.5 3283.12; … ; 0.0 0.0 … 5383.54 5433.77; 0.0 0.0 … 5332.44 5367.77]     [3920.27 3984.9 … 2949.7 3076.34; 3809.59 3906.7 … 3126.5 3119.12; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0]
 [0.0 0.0 … 3125.52 3203.08; 0.0 0.0 … 2908.5 3283.12; … ; 0.0 0.0 … 5383.54 5433.77; 0.0 0.0 … 5332.44 5367.77]     [3920.27 3984.9 … 2949.7 3076.34; 3809.59 3906.7 … 3126.5 3119.12; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0]
 [0.0 0.0 … 3125.52 3203.08; 0.0 0.0 … 2908.5 3283.12; … ; 0.0 0.0 … 5383.54 5433.77; 0.0 0.0 … 5332.44 5367.77]     [3920.27 3984.9 … 2949.7 3076.34; 3809.59 3906.7 … 3126.5 3119.12; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0]
```

**Comment by jbisits** [comment]
I can now see why `read_nctiles` does not work for my case above using ECCOv4r4 data. The files that I downloaded from ECCO drive do not match the naming that ECCOv4r2 and ECCOv4r3 have where there is a single folder with files named, e.g. for `UVELMASS`, `UVELMASS.xxxx.nc`. Instead I downloaded one of the monthly files from `files/Version4/Release4/nctiles_monthy/UVELMASS/1992` which is named `UVELMASS_1992_01.nc` and the function `read_nctiles` does not then work because after redefining `fileIn` it can no longer find the file saved on my computer.

Do you have any suggestions for what might be best for using ECCOv4r4 data with `MITgcmTools.jl`? I can download files and rename (this worked after renaming `UVELMASS_1992_01.nc`-> `UVELMASS.0001.nc`) to match the previous convention if that is better/easier than changing the function `read_nctiles`.

**Comment by gaelforget** [comment]
Please refer to https://github.com/gaelforget/MITgcmTools.jl/pull/69#issuecomment-1516310952
